export const INITIAL_PILOTHOURS = {
	crew: "",
	name: "",
	norme: { name: "", hoursToDo: 0, nightToDo: 0, duration: 0 },
	lastMonthDay: 0,
	lastMonthNight: 0,
	lastMonthTotal: 0,
	lastMonthSimpilTotal: 0,
	lastMonthSimpilNight: 0,
	sixLastMonthTotal: 0,
	sixLastMonthNight: 0,
	sixLastMonthTotalSimpil: 0,
	sixLastMonthNightSimpil: 0,
	twelveLastMonthTotal: 0,
	twelveLAstMonthNight: 0,
	hoursToDoThisMonthTotal: 0,
	hoursToDoThisMonthNight: 0,
	lastFlightdate: 0,
	lastSimpildate: 0,
}

export const INITAL_PILOT_HOURS = {
	id: "",
	type: "",
	effectiveDeparture: "",
	aircraft: 0,
	function: "",
	crew: "",
	mission: "",
	dayDuration: 0,
	nightDuration: 0,
	totalDuration: 0,
}
export const INITIAL_MYHOURS = {
	effectiveDeparture: "",
	aircraft: 0,
	CDA: "",
	crew: "",
	mission: "",
	done: "",
	cause: "",
	group: "",
	client: "",
	manager: "",
	dayDuration: 0,
	nightDuration: 0,
	totalDuration: 0,
}
export const INITIAL_SUMS = {
	flights: { day: 0, night: 0, total: 0 },
	simpils: { day: 0, night: 0, total: 0 },
}
